### ISSUE TITLE
Error backing up imagestream `Error uploading layer chunked: received unexpected HTTP status: 500 Internal Server Error`

### ISSUE THREAD

**Issue by kaovilai** [openshift/openshift-velero-plugin#101]
`Error writing blob: Error uploading layer chunked: received unexpected HTTP status: 500 Internal Server Error`
OADP Issue: https://github.com/openshift/oadp-operator/issues/163

Trying to reproduce.

**Comment by SergioTeco** [comment]
Hi I got that error too. And for other hand the svc route of oadp-backupstoragelocation-aws-registry is not available through web.
