### ISSUE TITLE
Taking a Backup from WorkLoad 

### ISSUE THREAD

**Issue by ahmedfaheem1980** [openshift/openshift-velero-plugin#49]
Hi All ,

We installed Openshift cluster , can we use Openshift plugin to take backup of CSI PV (without the need to use CSI plugin)

Can you please advise 
If not what are the exact Openshift objects , we can use  Openshift plugin to take a backup of 

Regards 
Ahmed Faheem

**Comment by dymurray** [comment]
@ahmedfaheem1980 This plugin is primarily used to provide any needed logic to properly restore OpenShift resources that Velero doesn't handle out of the box.

The CSI plugin published by Velero is independent of this plugin and can be used to take CSI snapshots of CSI volumes. If you choose not to use the CSI plugin then you will be forced to use Restic to take a backup of the CSI PV (which is totally fine).

This plugin is not used as a "here are the exact objects we will back up", but more that Velero will attempt to backup all the resources that match your included/excluded list and if any of those resources are openshift objects that require some special plugin logic to properly backup/restore then we handle it.

We are working on a definitive document that best explains each plugin's logic mechanisms but if you'd like to test out the latest version of this plugin I recommend using `docker.io/konveyor/openshift-velero-plugin:unified-repo` as it has some bug fixes we still need to merge into master.

**Comment by ahmedfaheem1980** [comment]
Thank you very much for your comment 

I hAVE COUPLE OF QUESTIONS : 1- Can we use OpenShift plugin to take back of CSI PV
Regrading Restic API, does it require any kind of customization to take CSI PV backup

Can you please give example of the OpenShift resources that can be b asked up
What is the required hardware specs /pods / do you have drafts version of the document you aRE REFERRING TO

**Comment by dymurray** [comment]
@ahmedfaheem1980 there's a separate CSI plugin that ships with Velero you can use.

Restic does not work with CSI, you have to use the CSI plugin.

Here's some docs describing each plugin: https://github.com/konveyor/openshift-velero-plugin#overview-of-each-plugin

**Comment by ahmedfaheem1980** [comment]
Hello
The said it is in beta version
  

 -----Dylan Murray ***@***.***> wrote: -----

 =======================
 To: konveyor/openshift-velero-plugin ***@***.***>
 From: Dylan Murray ***@***.***>
 Date: 06/16/2021 08:58PM 
 Cc: ahmedfaheem1980 ***@***.***>, Mention ***@***.***>
 Subject: [EXTERNAL] Re: [konveyor/openshift-velero-plugin] Taking a Backup from WorkLoad  (#49)
 =======================
   @ahmedfaheem1980 there's a separate CSI plugin that ships with Velero you can use.

Restic does not work with CSI, you have to use the CSI plugin.

Here's some docs describing each plugin: https://github.com/konveyor/openshift-velero-plugin#overview-of-each-plugin
