### ISSUE TITLE
Pod's SCC mismatch upon restore 

### ISSUE THREAD

**Issue by dymurray** [openshift/openshift-velero-plugin#50]
We encountered an issue in our testing where a pod running prior to backup did not get assigned to the same SCC when the pod was restored via Velero.

The pod running on the OCP cluster was assigned to the `anyuid` SCC due to being cluster-admin when the pod was created (default SCC for cluster-admin created resources is `anyuid`). At restore time, since the Velero SA is the user that creates the pod during the restore process the pod was instead assigned to the `restricted` SCC.

There are two potential solutions for this... the first is that the pod definition should include enough info about it's desired securityContext to prevent this from happening (this is if every application was written perfectly which we should guard against) and the second is that we may want to investigate if setting the SCC annotations on the resource itself forces OCP to schedule the pod in the same SCC.

**Comment by JaydipGabani** [comment]
Openshift replaces the `SCC` with `restricted` value even if we set the pod annotation `openshift.io/scc: anyuid` manually in pod restore plugin.
