### ISSUE TITLE
Restore ImageTag failed because of invalid Spec

### ISSUE THREAD

**Issue by phuongatemc** [openshift/openshift-velero-plugin#79]
Reproduce steps:
- Create hello world example project:  oc new-app https://github.com/openshift/ruby-hello-world.git#beta4 and wait for Build completes.   There are 2 ImageTag created.  ruby-22-centos7:latest (pull from docker.io) and reby-hello-world:latest (built by this example application).
[core@irv-12-181 ~]$ oc get imagetag
NAME                      SPEC   STATUS                                                                          HISTORY   UPDATED
ruby-22-centos7:latest    Tag    image/sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae   1         5 hours ago
ruby-hello-world:latest   Push   image/sha256:336a77fcc5f3509a9590692b61d237e88704ed6a4d69b40f4ff99acc8c48f32d   1         5 hours ago

- Backup the namespace using Data Domain BSL
- Restore to a different namespace "ph-hello-restore-5" ==> Hit error when restore ImageTag "ruby-hello-world:latest" 
...
time="2021-05-04T14:26:47Z" level=info msg="[common-restore] common restore plugin for ruby-hello-world:latest" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/restore.go:30" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-07-26-47-ph-hello-restore-5
time="2021-05-04T14:26:48Z" level=info msg="[GetRegistryInfo] value from imagestream" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/shared.go:35" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-07-26-47-ph-hello-restore-5
time="2021-05-04T14:26:48Z" level=info msg="[common-restore] Error getting registry route, assuming this is outside of OADP context." cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/restore.go:52" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-07-26-47-ph-hello-restore-5
time="2021-05-04T14:26:48Z" level=info msg="Attempting to restore ImageTag: ruby-hello-world:latest" logSource="pkg/restore/restore.go:1107" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-07-26-47-ph-hello-restore-5
time="2021-05-04T14:26:48Z" level=info msg="error restoring ruby-hello-world:latest: ImageTag.image.openshift.io \"ruby-hello-world:latest\" is invalid: spec: Required value: spec is a required field during creation" logSource="pkg/restore/restore.go:1170" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-07-26-47-ph-hello-restore-5

**Comment by sseago** [comment]
We have an ImageTag plugin which abandons the ImageTag restore to get around this problem. ImageTags  serve the same basic function as ImageStreamTags, but my understanding is that ImageTags will eventually supercede them. For the moment, though, creating one creates the other, so there's no reason to restore both of them. For recent MTC versions, we've disabled this plugin to get around a velero bug -- the ImageTag plugin ends up being registered for *all* types in a cluster where ImageTags don't exist (OCP4.3 and older), which resulted in everything being discarded, not just ImageTags. If you're using a build of openshift-velero-plugin with this disabled, you can get the same effect by including imagetags in the exclude resources list for the backup.

**Comment by sseago** [comment]
Once we hit a point where there's actually information in the ImageTag that we want to restore that is *not* handled by restoring the ImageStreamTag, we may need more than just abandoning the ImageTag in the plugin, but for the moment, I haven't seen anything that we lose by just restoring the ImageStreamTag. I do need to go back and figure out why the ImageTag plugin isn't working with velero upstream -- it's also possible that with Velero 1.6 the problem has gone away.

**Comment by phuongatemc** [comment]
I tested the latest release Velero 1.6 with the OpenShift plugin 1.4.4 and still saw the same error:

# oc get pod -n velero-ppdm velero-559ffd7876-7k96q -o yaml
...
  - containerID: cri-o://1e716744f973c4c2f16ae536fac8d35547dadf46d968d218de784093f61e990d
    image: ap-sc.sc.ops.delllabs.net:8446/velero/velero:v1.6.0
    imageID: ap-sc.sc.ops.delllabs.net:8446/velero/velero@sha256:14d914efc313705f6b9487c1fa70bb05adbf47c126036fbca05b597058f5bdd1
  initContainerStatuses:
...
  - containerID: cri-o://930e6ae603860c48add512c2cd9f34c6e9949932ee669e814be3158964caf33e
    image: quay.io/konveyor/openshift-velero-plugin:release-1.4.4
    imageID: quay.io/konveyor/openshift-velero-plugin@sha256:332514d0b71a9e3942bffcf6d935df97a1f3231773590aae285e33f160b97ee9
 ...

**Comment by sseago** [comment]
@phuongatemc Thanks for letting me know it's still there with 1.6. We first noticed this problem with either velero 1.3 or 1.4 (I can't remember which), and there was an upstream fix that resolved the issue. I suspect that some upstream refactoring reintroduced the bug. I need to set aside some time later this week to find and fix it again upstream and submit an upstream PR.

**Comment by phuongatemc** [comment]
I notice in the log that there are 2 ImageTags being restored.  The first one restore without problem.  The second ImageTag failed.  I also notice that it execute the "common-restore" instead of the "imagetag-restore".  The source code of ImageTag plugin shows it returns "velero.NewRestoreItemActionExecuteOutput(input.Item).WithoutRestore(), nil" but it looks like this ImageTag function is not executed.
Here is the log:
time="2021-05-04T16:46:39Z" level=info msg="Getting client for image.openshift.io/v1, Kind=ImageTag" logSource="pkg/restore/restore.go:768" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:39Z" level=info msg="**Executing item action for imagetags.image.openshift.io**" logSource="pkg/restore/restore.go:1002" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:39Z" level=info msg="**[common-restore]** Entering common restore plugin" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/restore.go:23" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:39Z" level=info msg="[common-restore] common restore plugin for **ruby-22-centos7:latest**" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/restore.go:30" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="[GetRegistryInfo] value from imagestream" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/shared.go:35" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="[common-restore] Error getting registry route, assuming this is outside of OADP context." cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/restore.go:52" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="Attempting to restore ImageTag: ruby-22-centos7:latest" logSource="pkg/restore/restore.go:1107" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="Executing item action for imagetags.image.openshift.io" logSource="pkg/restore/restore.go:1002" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="[**common-restore**] Entering common restore plugin" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/restore.go:23" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="[common-restore] common restore plugin for **ruby-hello-world:latest**" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/restore.go:30" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="[GetRegistryInfo] value from imagestream" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/shared.go:35" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="[common-restore] Error getting registry route, assuming this is outside of OADP context." cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/restore.go:52" pluginName=velero-plugins restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="Attempting to restore ImageTag: ruby-hello-world:latest" logSource="pkg/restore/restore.go:1107" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" **level=info msg="error restoring ruby-hello-world:latest: ImageTag.image.openshift.io \"ruby-hello-world:latest\" is invalid: spec: Required value: spec is a required field during creation"** logSource="pkg/restore/restore.go:1170" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
time="2021-05-04T16:46:40Z" level=info msg="Restoring resource 'replicationcontrollers' into namespace 'ph-hello-restore-5'" logSource="pkg/restore/restore.go:724" restore=velero-ppdm/aed4b4d2-cf98-533e-b531-de235a1b8213-2021-05-04-09-46-34-ph-hello-restore-5
