### ISSUE TITLE
Could the s390x be added to the architecture supported by the velero plugin?

### ISSUE THREAD

**Issue by jwyoon-darum** [openshift/openshift-velero-plugin#82]
Hello,

Currently, Openshift is being configured and used in **IBM Z(s390x)** equipment. I want to use velero to backup and restore my Openshift cluster, but I don't have an **s390x** container image.
I am wondering if there are plans to be added or if there is a way to create a container image.

Thank you.

**Comment by dymurray** [comment]
@jwyoon-darum not sure I understand. We ship the plugin as a container that is based on UBI, but you can run adn deploy this in any OCP cluster. Why do you need the image built on s390x?
