### ISSUE TITLE
OADP-1004: Pods with a restic backup are excluded from being restored when they have no backup annotation

### ISSUE THREAD

**Issue by bo0ts** [openshift/openshift-velero-plugin#96]
I've reported https://github.com/openshift/oadp-operator/issues/158 but it seems that this is a issue with the `openshift-velero-plugin`. Feel free to ask for additional information if the linked issue isn't sufficient.

**Comment by sseago** [comment]
@bo0ts Yes, this is an issue in the plugin. Pods with owner references are normally excluded from the restore when they have owner references (since the deployment, etc. will recreate them anyway). But we make an exception to this for pods with restic annotations -- at the time this plugin code was developed, restic annotations were the only way to trigger restic backups. The "default to restic" option is newer, and the plugin didn't follow through. We need to also make an exception for all pods with volumes if the "default to restic" option is enabled.

**Comment by DoGab** [comment]
I have encountered the same problem. The volume was correctly backuped using restic into the S3 bucket and a `podvolumebackup` resource was created. But after the restore no `podvolumerestore` resource was created and the volume was not restored. When will this be fixed?

When annotating the pods like in previous velero versions and described [here](https://velero.io/docs/v1.6/restic/#to-back-up) the restore works.

**Comment by madchr1st** [comment]
I am hitting the same issue.

When using `defaultVolumesToRestic` in the backup CR, the volumes are backed up correctly with restic, but the volumes are not restored afterwards (only recreated, empty).

With the restore only working with the use of pod annotations, this is IMHO not suitable for production at the moment.

Is there any way we can support you in resolving this issue?

**Comment by DoGab** [comment]
When is this going to be fixed? Still an issue with the "stable" version of ADP.

**Comment by kaovilai** [comment]
>volumes are not restored afterwards (only recreated, empty).

I wonder if the pod that was restored with data got killed in favor of a different pod created by owners (deployment etc.)

**Comment by louise-zhang** [comment]
Hi there, is there any update on this issue? I am experiencing the same issue as @[DoGab](https://github.com/DoGab) https://github.com/openshift/openshift-velero-plugin/issues/96#issuecomment-927847343

**Comment by kaovilai** [comment]
For those that do not require restic, try to use CSI snapshot instead which is working now.

Example in [oadp blog](https://tig.pw/oadp-blog)

**Comment by louise-zhang** [comment]
I think this issue has been resolved with latest OADP operator: oadp-operator.v1.0.2 
Have tested backup and restore volume without adding pod annotations, backup and restore are successful. (it didn't work with oadp-operator.v1.0.1)

**Comment by VphDreamer** [comment]
Hello, I am having the same issue using oadp-operator v1.0.3

**Comment by kaovilai** [comment]
Can you all confirm if problem exists in 1.1?

**Comment by kaovilai** [comment]
IIUC this was fixed in https://github.com/openshift/openshift-velero-plugin/pull/102 and is duped of https://github.com/openshift/oadp-operator/issues/74 closing.
